version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    command: sh -c "yarn && yarn dev"
    ports:
      - "5173:5173"
    stdin_open: true 
